import {
  Home,
  Users,
  Building2,
  BarChart3,
  MessageSquare,
  Calendar,
  FileText,
  GitBranch,
  Activity,
  Database,
  Shield,
  Settings,
  CircleEllipsis,
  Briefcase,
  Target,
  TrendingUp,
  Package,
  UserPlus,
  Phone,
  Mail,
  Map,
  Clock,
  CheckSquare,
  Upload,
  Download,
  Filter,
  Zap,
  UserCheck,
  FolderOpen,
  Tags,
  DollarSign,
  Star,
  Archive,
  Search,
  ClipboardList,
  Layers,
  UserCog,
  Workflow,
  Globe,
  Send,
  Inbox
} from 'lucide-react';
import { type NavConfig } from './types';

export const LEADS_NAV: NavConfig = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: Home,
    path: '/leads/dashboard',
    pinned: true,
  },
  {
    id: 'leads',
    title: 'All Leads',
    icon: Users,
    path: '/leads/list',
    pinnable: true,
    pinned: true,
    badge: '24',
    more: true,
    new: {
      tooltip: 'Add New Lead',
      path: '/leads/add',
    },
  },
  {
    id: 'my-leads',
    title: 'My Leads',
    icon: UserCheck,
    path: '/leads/my-leads',
    pinnable: true,
    pinned: true,
    badge: '12',
  },
  {
    id: 'lead-capture',
    title: 'Lead Capture',
    icon: Inbox,
    path: '/leads/capture',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Capture Form',
      path: '/leads/capture/new',
    },
  },
  {
    id: 'pipeline',
    title: 'Pipeline', 
    icon: GitBranch,
    path: '/leads/pipeline',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Pipeline Stage',
      path: '/leads/pipeline/new',
    },
  },
  {
    id: 'qualification',
    title: 'Qualification',
    icon: ClipboardList,
    path: '/leads/qualification',
    pinnable: true,
    pinned: true,
    badge: '5',
  },
  {
    id: 'scoring',
    title: 'Lead Scoring',
    icon: Star,
    path: '/leads/scoring',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'assignment',
    title: 'Assignment Rules',
    icon: UserCog,
    path: '/leads/assignment',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: CheckSquare,
    path: '/leads/tasks',
    pinnable: true,
    pinned: true,
    badge: '8',
    more: true,
    new: {
      tooltip: 'New Task',
      path: '/leads/tasks/new',
    },
  },
  {
    id: 'follow-ups',
    title: 'Follow-ups',
    icon: Clock,
    path: '/leads/follow-ups',
    pinnable: true,
    pinned: true,
    badge: '6',
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: MessageSquare,
    path: '/leads/communication',
    pinnable: true,
    pinned: true,
    badge: '3',
    new: {
      tooltip: 'New Message',
      path: '/leads/communication/new',
    },
  },
  {
    id: 'email-campaigns',
    title: 'Email Campaigns',
    icon: Send,
    path: '/leads/campaigns',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Campaign',
      path: '/leads/campaigns/new',
    },
  },
  {
    id: 'calendar',
    title: 'Calendar',
    icon: Calendar,
    path: '/leads/calendar',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Event',
      path: '/leads/calendar/new',
    },
  },
  {
    id: 'companies',
    title: 'Companies',
    icon: Building2,
    path: '/leads/companies',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Company',
      path: '/leads/companies/new',
    },
  },
  {
    id: 'deals',
    title: 'Deals',
    icon: Briefcase,
    path: '/leads/deals',
    pinnable: true,
    pinned: true,
    badge: '7',
    new: {
      tooltip: 'New Deal',
      path: '/leads/deals/new',
    },
  },
  {
    id: 'quotes',
    title: 'Quotes',
    icon: DollarSign,
    path: '/leads/quotes',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Quote',
      path: '/leads/quotes/new',
    },
  },
  {
    id: 'categories',
    title: 'Categories',
    icon: Tags,
    path: '/leads/categories',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'sources',
    title: 'Lead Sources',
    icon: Globe,
    path: '/leads/sources',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'activities',
    title: 'Activities',
    icon: Activity,
    path: '/leads/activities',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'documents',
    title: 'Documents',
    icon: FileText,
    path: '/leads/documents',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'Upload Document',
      path: '/leads/documents/upload',
    },
  },
  {
    id: 'analytics',
    title: 'Analytics',
    icon: BarChart3,
    path: '/leads/analytics',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: TrendingUp,
    path: '/leads/reports',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'automation',
    title: 'Automation',
    icon: Zap,
    path: '/leads/automation',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'workflows',
    title: 'Workflows',
    icon: Workflow,
    path: '/leads/workflows',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Workflow',
      path: '/leads/workflows/new',
    },
  },
  {
    id: 'archive',
    title: 'Archived',
    icon: Archive,
    path: '/leads/archive',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'settings',
    title: 'Settings',
    icon: Settings,
    path: '/leads/settings',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'more',
    title: 'More',
    icon: CircleEllipsis,
    dropdown: true,
  },
];