import {
  Home,
  Users,
  Building2,
  BarChart3,
  MessageSquare,
  Calendar,
  FileText,
  GitBranch,
  Activity,
  Database,
  Shield,
  Settings,
  CircleEllipsis,
  Briefcase,
  Target,
  TrendingUp,
  Package,
  UserPlus,
  Phone,
  Mail,
  Map,
  Clock,
  CheckSquare,
  Upload,
  Download,
  Filter,
  Zap
} from 'lucide-react';
import { type NavConfig } from './types';

export const LEADS_NAV: NavConfig = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: Home,
    path: '/leads/dashboard',
    pinned: true,
  },
  {
    id: 'leads',
    title: 'Leads',
    icon: Users,
    path: '/leads/list',
    pinnable: true,
    pinned: true,
    badge: '24',
    more: true,
    new: {
      tooltip: 'Add New Lead',
      path: '/leads/add',
    },
  },
  {
    id: 'pipeline',
    title: 'Pipeline', 
    icon: GitBranch,
    path: '/leads/pipeline',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Pipeline Stage',
      path: '/leads/pipeline/new',
    },
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: CheckSquare,
    path: '/leads/tasks',
    pinnable: true,
    pinned: true,
    badge: '8',
    more: true,
    new: {
      tooltip: 'New Task',
      path: '/leads/tasks/new',
    },
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: MessageSquare,
    path: '/leads/communication',
    pinnable: true,
    pinned: true,
    badge: '3',
    new: {
      tooltip: 'New Message',
      path: '/leads/communication/new',
    },
  },
  {
    id: 'calendar',
    title: 'Calendar',
    icon: Calendar,
    path: '/leads/calendar',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Event',
      path: '/leads/calendar/new',
    },
  },
  {
    id: 'analytics',
    title: 'Analytics',
    icon: BarChart3,
    path: '/leads/analytics',
    pinnable: true,
    pinned: true,
  },
  {
    id: 'companies',
    title: 'Companies',
    icon: Building2,
    path: '/leads/companies',
    pinnable: true,
    pinned: true,
    new: {
      tooltip: 'New Company',
      path: '/leads/companies/new',
    },
  },
  {
    id: 'deals',
    title: 'Deals',
    icon: Briefcase,
    path: '/leads/deals',
    pinnable: true,
    pinned: false,
    new: {
      tooltip: 'New Deal',
      path: '/leads/deals/new',
    },
  },
  {
    id: 'activities',
    title: 'Activities',
    icon: Activity,
    path: '/leads/activities',
    pinnable: true,
    pinned: false,
  },
  {
    id: 'documents',
    title: 'Documents',
    icon: FileText,
    path: '/leads/documents',
    pinnable: true,
    pinned: false,
    new: {
      tooltip: 'Upload Document',
      path: '/leads/documents/upload',
    },
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: TrendingUp,
    path: '/leads/reports',
    pinnable: true,
    pinned: false,
  },
  {
    id: 'automation',
    title: 'Automation',
    icon: Zap,
    path: '/leads/automation',
    pinnable: true,
    pinned: false,
  },
  {
    id: 'more',
    title: 'More',
    icon: CircleEllipsis,
    dropdown: true,
  },
];