import {
  Home,
  Users,
  Building2,
  BarChart3,
  MessageSquare,
  Calendar,
  FileText,
  GitBranch,
  Activity,
  Database,
  Shield,
  Settings,
  CircleEllipsis,
  Briefcase,
  Target,
  TrendingUp,
  Package,
  UserPlus,
  Phone,
  Mail,
  Map,
  Clock,
  CheckSquare,
  Upload,
  Download,
  Filter,
  Zap,
  UserCheck,
  FolderOpen,
  Tags,
  DollarSign,
  Star,
  Archive,
  Search,
  ClipboardList,
  Layers,
  UserCog,
  Workflow,
  Globe,
  Send,
  Inbox,
  List,
  Grid3x3,
  Plus,
  FileInput,
  MapPin,
  GitPullRequest,
  Flag,
  CheckCircle,
  Trophy,
  UserPlus2,
  ListTodo,
  CalendarCheck,
  CalendarClock,
  ActivitySquare,
  History,
  MessageCircle,
  PenTool,
  FileCode,
  Megaphone,
  MessageSquareText,
  Smartphone,
  PhoneCall,
  Handshake,
  FileSignature,
  Calculator,
  LineChart,
  PieChart,
  FileBarChart,
  FileLineChart,
  FileCheck,
  Wand2,
  Zap as Lightning,
  FolderTree,
  BookOpen,
  LogIn,
  Cog,
  LayoutList,
  Tag,
  Factory,
  MapPinned,
  Link
} from 'lucide-react';
import { type NavConfig } from './types';

export const LEADS_NAV: NavConfig = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: Home,
    path: '/leads/dashboard',
    pinned: true,
  },
  {
    id: 'leads-management',
    title: 'Lead Management',
    icon: Users,
    pinned: true,
    children: [
      {
        id: 'all-leads',
        title: 'All Leads',
        icon: List,
        path: '/leads/list',
        badge: '24',
      },
      {
        id: 'lead-board',
        title: 'Lead Board',
        icon: Grid3x3,
        path: '/leads/board',
        badge: '12',
      },
      {
        id: 'new-lead',
        title: 'Add New Lead',
        icon: Plus,
        path: '/leads/add',
      },
      {
        id: 'lead-capture',
        title: 'Lead Capture Forms',
        icon: FileInput,
        path: '/leads/forms',
      },
      {
        id: 'import-leads',
        title: 'Import/Export',
        icon: Download,
        path: '/leads/import-export',
      },
      {
        id: 'lead-map',
        title: 'Map View',
        icon: MapPin,
        path: '/leads/map',
      },
    ],
  },
  {
    id: 'pipeline-management',
    title: 'Pipeline',
    icon: GitBranch,
    pinned: true,
    children: [
      {
        id: 'pipeline-view',
        title: 'Pipeline View',
        icon: GitPullRequest,
        path: '/leads/pipeline',
      },
      {
        id: 'stages',
        title: 'Lead Stages',
        icon: Flag,
        path: '/leads/lead-stages',
      },
      {
        id: 'statuses',
        title: 'Lead Statuses',
        icon: CheckCircle,
        path: '/leads/lead-statuses',
        badge: '5',
      },
      {
        id: 'scoring',
        title: 'Scoring Rules',
        icon: Trophy,
        path: '/leads/master-data/scoring-rules',
      },
      {
        id: 'assignment',
        title: 'Assignment Rules',
        icon: UserPlus2,
        path: '/leads/master-data/assignment-rules',
      },
    ],
  },
  {
    id: 'activities',
    title: 'Activities',
    icon: CheckSquare,
    pinned: true,
    children: [
      {
        id: 'tasks',
        title: 'Task Management',
        icon: ListTodo,
        path: '/leads/additional/task-management',
        badge: '8',
      },
      {
        id: 'follow-ups',
        title: 'Follow-up Manager',
        icon: CalendarCheck,
        path: '/leads/additional/follow-up-manager',
        badge: '6',
      },
      {
        id: 'meetings',
        title: 'Meeting Scheduler',
        icon: CalendarClock,
        path: '/leads/additional/meeting-scheduler',
      },
      {
        id: 'timeline',
        title: 'Activity Timeline',
        icon: History,
        path: '/leads/timeline',
      },
      {
        id: 'activity-mgmt',
        title: 'Activity Management',
        icon: ActivitySquare,
        path: '/leads/additional/activity-management',
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: MessageSquare,
    pinned: true,
    children: [
      {
        id: 'comm-hub',
        title: 'Communication Hub',
        icon: MessageCircle,
        path: '/leads/communication/hub',
        badge: '3',
      },
      {
        id: 'email-composer',
        title: 'Email Composer',
        icon: PenTool,
        path: '/leads/communication/email-composer',
      },
      {
        id: 'email-templates',
        title: 'Email Templates',
        icon: FileCode,
        path: '/leads/communication/email-templates',
      },
      {
        id: 'campaigns',
        title: 'Email Campaigns',
        icon: Megaphone,
        path: '/leads/communication/campaigns',
      },
      {
        id: 'sms',
        title: 'SMS Center',
        icon: MessageSquareText,
        path: '/leads/communication/sms',
      },
      {
        id: 'whatsapp',
        title: 'WhatsApp',
        icon: Smartphone,
        path: '/leads/communication/whatsapp',
      },
      {
        id: 'call-center',
        title: 'Call Center',
        icon: PhoneCall,
        path: '/leads/communication/call-center',
      },
    ],
  },
  {
    id: 'calendar',
    title: 'Calendar',
    icon: Calendar,
    path: '/leads/calendar',
    pinned: true,
  },
  {
    id: 'sales',
    title: 'Sales',
    icon: Briefcase,
    pinned: true,
    children: [
      {
        id: 'deals',
        title: 'Deal Tracking',
        icon: Handshake,
        path: '/leads/sales/deals',
        badge: '7',
      },
      {
        id: 'opportunities',
        title: 'Opportunities',
        icon: Target,
        path: '/leads/sales/opportunities',
      },
      {
        id: 'quotes',
        title: 'Quote Generator',
        icon: Calculator,
        path: '/leads/additional/quote-generator',
      },
      {
        id: 'proposals',
        title: 'Proposals',
        icon: FileSignature,
        path: '/leads/sales/proposals',
      },
      {
        id: 'contracts',
        title: 'Contracts',
        icon: FileCheck,
        path: '/leads/sales/contracts',
      },
      {
        id: 'forecasting',
        title: 'Sales Forecasting',
        icon: LineChart,
        path: '/leads/sales/forecasting',
      },
    ],
  },
  {
    id: 'companies',
    title: 'Companies',
    icon: Building2,
    path: '/leads/companies',
    pinned: true,
  },
  {
    id: 'analytics',
    title: 'Analytics & Reports',
    icon: BarChart3,
    pinned: true,
    children: [
      {
        id: 'dashboard-analytics',
        title: 'Analytics Dashboard',
        icon: PieChart,
        path: '/leads/analytics/dashboard',
      },
      {
        id: 'sales-dashboard',
        title: 'Sales Dashboard',
        icon: TrendingUp,
        path: '/leads/analytics/sales-dashboard',
      },
      {
        id: 'report-builder',
        title: 'Report Builder',
        icon: FileBarChart,
        path: '/leads/analytics/report-builder',
      },
      {
        id: 'standard-reports',
        title: 'Standard Reports',
        icon: FileLineChart,
        path: '/leads/analytics/standard-reports',
      },
      {
        id: 'custom-reports',
        title: 'Custom Reports',
        icon: FileCheck,
        path: '/leads/analytics/custom-reports',
      },
    ],
  },
  {
    id: 'documents',
    title: 'Documents',
    icon: FileText,
    path: '/leads/additional/document-management',
    pinned: true,
  },
  {
    id: 'automation',
    title: 'Automation',
    icon: Zap,
    pinned: true,
    children: [
      {
        id: 'workflow-builder',
        title: 'Workflow Builder',
        icon: Workflow,
        path: '/leads/automation/workflow-builder',
      },
      {
        id: 'triggers',
        title: 'Trigger Events',
        icon: Lightning,
        path: '/leads/automation/triggers',
      },
      {
        id: 'templates',
        title: 'Nurturing Templates',
        icon: FolderTree,
        path: '/leads/automation/templates/nurturing',
      },
      {
        id: 'automation-analytics',
        title: 'Workflow Analytics',
        icon: Activity,
        path: '/leads/automation/analytics',
      },
      {
        id: 'automation-logs',
        title: 'Automation Logs',
        icon: BookOpen,
        path: '/leads/automation/logs',
      },
    ],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    icon: Settings,
    pinned: true,
    children: [
      {
        id: 'general-settings',
        title: 'General Settings',
        icon: Cog,
        path: '/leads/admin/general-settings',
      },
      {
        id: 'lead-sources',
        title: 'Lead Sources',
        icon: LogIn,
        path: '/leads/master-data/lead-sources',
      },
      {
        id: 'categories',
        title: 'Lead Categories',
        icon: Tag,
        path: '/leads/master-data/lead-categories',
      },
      {
        id: 'industries',
        title: 'Industries',
        icon: Factory,
        path: '/leads/master-data/industries',
      },
      {
        id: 'territories',
        title: 'Territories',
        icon: MapPinned,
        path: '/leads/territories',
      },
      {
        id: 'integrations',
        title: 'Integrations',
        icon: Link,
        path: '/leads/admin/integrations',
      },
    ],
  },
  {
    id: 'archive',
    title: 'Archive',
    icon: Archive,
    path: '/leads/archive',
    pinned: true,
  },
  {
    id: 'more',
    title: 'More',
    icon: CircleEllipsis,
    dropdown: true,
  },
];