import {
  LayoutGrid,
  FolderOpen,
  Kanban,
  CheckSquare,
  GitBranch,
  BarChart3,
  Clock,
  FileText,
  Users,
  Calendar,
  MessageSquare,
  TrendingUp,
  Settings,
  Package,
  Target,
  AlertCircle,
  DollarSign,
  Briefcase,
  Archive,
  MoreHorizontal,
  Zap,
  Shield,
  Database,
  HelpCircle,
  UserCheck,
  FileSearch,
  GitPullRequest,
  Activity
} from 'lucide-react';
import type { NavItem } from './types';

export const projectNavItems: NavItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/projects/dashboard',
    icon: LayoutGrid,
    pinned: true,
  },
  {
    id: 'projects',
    title: 'Projects',
    icon: FolderOpen,
    pinned: true,
    children: [
      {
        id: 'all-projects',
        title: 'All Projects',
        path: '/projects/list',
        icon: FolderOpen,
      },
      {
        id: 'active-projects',
        title: 'Active Projects',
        path: '/projects/active',
        icon: Activity,
      },
      {
        id: 'archived-projects',
        title: 'Archived',
        path: '/projects/archived',
        icon: Archive,
      },
      {
        id: 'templates',
        title: 'Templates',
        path: '/projects/templates',
        icon: Package,
      },
    ],
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: CheckSquare,
    pinned: true,
    children: [
      {
        id: 'all-tasks',
        title: 'All Tasks',
        path: '/projects/tasks',
        icon: CheckSquare,
      },
      {
        id: 'my-tasks',
        title: 'My Tasks',
        path: '/projects/tasks/mine',
        icon: UserCheck,
        badge: '12',
      },
      {
        id: 'kanban-board',
        title: 'Kanban Board',
        path: '/projects/kanban',
        icon: Kanban,
      },
      {
        id: 'gantt-chart',
        title: 'Gantt Chart',
        path: '/projects/gantt',
        icon: BarChart3,
      },
    ],
  },
  {
    id: 'milestones',
    title: 'Milestones',
    path: '/projects/milestones',
    icon: GitBranch,
    pinned: true,
    badge: '3',
  },
  {
    id: 'timeline',
    title: 'Timeline',
    path: '/projects/timeline',
    icon: Clock,
    pinned: true,
  },
  {
    id: 'team',
    title: 'Team',
    icon: Users,
    pinned: true,
    children: [
      {
        id: 'team-members',
        title: 'Members',
        path: '/projects/team/members',
        icon: Users,
      },
      {
        id: 'workload',
        title: 'Workload',
        path: '/projects/team/workload',
        icon: Activity,
      },
      {
        id: 'assignments',
        title: 'Assignments',
        path: '/projects/team/assignments',
        icon: UserCheck,
      },
    ],
  },
  {
    id: 'documents',
    title: 'Documents',
    icon: FileText,
    pinned: false,
    children: [
      {
        id: 'all-documents',
        title: 'All Files',
        path: '/projects/documents',
        icon: FileText,
      },
      {
        id: 'requirements',
        title: 'Requirements',
        path: '/projects/documents/requirements',
        icon: FileSearch,
      },
      {
        id: 'specifications',
        title: 'Specifications',
        path: '/projects/documents/specs',
        icon: FileText,
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: MessageSquare,
    pinned: false,
    children: [
      {
        id: 'discussions',
        title: 'Discussions',
        path: '/projects/discussions',
        icon: MessageSquare,
      },
      {
        id: 'meetings',
        title: 'Meetings',
        path: '/projects/meetings',
        icon: Calendar,
      },
      {
        id: 'notes',
        title: 'Notes',
        path: '/projects/notes',
        icon: FileText,
      },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: TrendingUp,
    pinned: false,
    children: [
      {
        id: 'progress-report',
        title: 'Progress Report',
        path: '/projects/reports/progress',
        icon: TrendingUp,
      },
      {
        id: 'budget-report',
        title: 'Budget Report',
        path: '/projects/reports/budget',
        icon: DollarSign,
      },
      {
        id: 'risk-report',
        title: 'Risk Analysis',
        path: '/projects/reports/risks',
        icon: AlertCircle,
      },
    ],
  },
  {
    id: 'resources',
    title: 'Resources',
    icon: Package,
    pinned: false,
    children: [
      {
        id: 'budget',
        title: 'Budget',
        path: '/projects/resources/budget',
        icon: DollarSign,
      },
      {
        id: 'assets',
        title: 'Assets',
        path: '/projects/resources/assets',
        icon: Package,
      },
      {
        id: 'allocations',
        title: 'Allocations',
        path: '/projects/resources/allocations',
        icon: Target,
      },
    ],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    path: '/projects/integrations',
    icon: Zap,
    pinned: false,
  },
  {
    id: 'security',
    title: 'Security',
    path: '/projects/security',
    icon: Shield,
    pinned: false,
  },
  {
    id: 'archive',
    title: 'Archive',
    path: '/projects/archive',
    icon: Archive,
    pinned: false,
  },
  {
    id: 'settings',
    title: 'Settings',
    path: '/projects/settings',
    icon: Settings,
    pinned: false,
  },
  {
    id: 'help',
    title: 'Help & Support',
    path: '/projects/help',
    icon: HelpCircle,
    pinned: false,
  },
  {
    id: 'more',
    title: 'More',
    icon: MoreHorizontal,
    dropdown: true,
    pinned: false,
    pinnable: false,
  },
];